spring:
  application:
    name: user_center


# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 24211
    url: jdbc:mysql://localhost:3306/user_center

  # session 失效时间
  session:
    timeout: 86400

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl