spring:
  application:
    name: user_center

# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 24211
    url: jdbc:mysql://localhost:3306/user_center
